export const SEARCH = 'SEARCH';
export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_FULFILLED = 'SEARCH_FULFILLED';
export const SEARCH_REJECTED = 'SEARCH_REJECTED';

export const FETCH_BOOK = 'FETCH_BOOK';
export const FETCH_BOOK_PENDING = 'FETCH_BOOK_PENDING';
export const FETCH_BOOK_FULFILLED = 'FETCH_BOOK_FULFILLED';
export const FETCH_BOOK_REJECTED = 'FETCH_BOOK_REJECTED';